export const sampleTransactions = [
  {
    id: 1,
    title: "Monthly Salary",
    amount: 50000,
    type: "income",
    category: "Salary",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "Grocery Shopping",
    amount: 2500,
    type: "expense",
    category: "Food",
    date: "2025-07-03",
  },
  {
    id: 3,
    title: "Netflix Subscription",
    amount: 499,
    type: "expense",
    category: "Entertainment",
    date: "2025-02-05",
  },
  {
    id: 4,
    title: "Freelance Project",
    amount: 15000,
    type: "income",
    category: "Freelance",
    date: "2025-01-08",
  },
  {
    id: 5,
    title: "Electricity Bill",
    amount: 1800,
    type: "expense",
    category: "Bills",
    date: "2025-01-10",
  },
  {
    id: 6,
    title: "Fixed Deposit",
    amount: 10000,
    type: "savings",
    category: "Investment",
    date: "2025-01-12",
  },
  {
    id: 7,
    title: "Zomato Order",
    amount: 650,
    type: "expense",
    category: "Food",
    date: "2025-01-14",
  },
  {
    id: 8,
    title: "Mutual Fund",
    amount: 5000,
    type: "savings",
    category: "Investment",
    date: "2025-01-16",
  },
  {
    id: 9,
    title: "Petrol",
    amount: 1200,
    type: "expense",
    category: "Transport",
    date: "2025-01-18",
  },
  {
    id: 10,
    title: "YouTube Premium",
    amount: 129,
    type: "expense",
    category: "Entertainment",
    date: "2025-01-20",
  },
  {
    id: 11,
    title: "Swiggy Order",
    amount: 450,
    type: "expense",
    category: "Movie",
    date: "2025-01-22",
  },
  {
    id: 12,
    title: "Mobile Recharge",
    amount: 299,
    type: "expense",
    category: "shopping",
    date: "2025-01-24",
  },
  {
    id: 13,
    title: "Uber Ride",
    amount: 350,
    type: "expense",
    category: "Transport",
    date: "2025-01-26",
  },
  {
    id: 14,
    title: "Medicine",
    amount: 800,
    type: "expense",
    category: "Tour",
    date: "2025-01-28",
  },
];
